
#ifndef GASTON_H
#define GASTON_H

 
#define NUM_STATIONS 4
#define AVAILABLE_DRINKS 3
#define BATLOW 720   // ca. 11 volt
#define BATLOW_ALERTCOUNTER   100

#define DEFAULT_DARK_IR_VALUE  700
#define IR_DEADZONE  40

#define ORDER_TIMEOUT 15
#define SLEEP_TIMEOUT 6

#define TIME_FACTOR_WAIT_DELIVERY 600

#define LINEFOLLOW_SPEED 180
#define LINEFOLLOW_SPEED_STRAIGHT 120

#define AVERAGE_IR 10


#endif
